#!/bin/bash

xset r rate 200 25

# NOTE: IDs below are from `xinput list-props`

# Enable tapping
xinput set-prop "SynPS/2 Synaptics TouchPad" 282 1

# Disable tapping drag
xinput set-prop "SynPS/2 Synaptics TouchPad" 284 0

# Change acceleration
xinput set-prop "SynPS/2 Synaptics TouchPad" 302 0.3

exec i3
