#!/bin/bash

xset r rate 200 25

# NOTE: IDs below are from `xinput list-props`

# Increase speed
xinput set-prop "SynPS/2 Synaptics TouchPad" 149 2.000000, 0.000000, 0.000000, 0.000000, 2.000000, 0.000000, 0.000000, 0.000000, 1.000000

# Enable tapping
xinput set-prop "SynPS/2 Synaptics TouchPad" 282 1

# Disable tapping drag
xinput set-prop "SynPS/2 Synaptics TouchPad" 284 0

exec i3
