#!/bin/bash

xset r rate 200 25

# NOTE: IDs below are from `xinput list-props`

# Increase speed
xinput set-prop "SynPS/2 Synaptics TouchPad" "Coordinate Transformation Matrix" 2.000000, 0.000000, 0.000000, 0.000000, 2.000000, 0.000000, 0.000000, 0.000000, 1.000000

# Enable tapping
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1

# Disable tapping drag
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Drag Enabled" 0

# Disable "beeps"
xset b off

exec i3
