alias claude="cd ~/Workspace/nodejs/ClaudeBot/"
alias enactus="cd ~/Workspace/nodejs/Enactus/"
alias goproj="cd ~/Workspace/golang/src/github.com/mrsaints/"
alias arachnys="cd ~/Workspace/nodejs/Arachnys/Website/"
alias foodfly="cd ~/Workspace/ruby/foodfly/"
