[git_status]
disabled=true

[aws]
disabled=true

[gcloud]
disabled=true

[golang]
disabled=true

[nodejs]
disabled=true

[python]
disabled=true

[rust]
disabled=true

[package]
disabled=true

[kubernetes]
disabled=false
